conda_forge_output_validation: true
build_platform:
  linux_aarch64: linux_64
  linux_ppc64le: linux_64
  osx_arm64: osx_64
test: native
build_with_mambabuild: false
github:
  branch_name: main
  tooling_branch_name: main
